# baseURL = 'https://biometriaforestal.uchile.cl/'
# Se pone esta url por motivos de testing
## hugo.drimyswinteri.org'
baseURL = 'https://miniature-happiness.github.io'
languageCode = 'es-CL'
title = 'Laboratorio de Biometría y Modelación Forestal'
theme = 'ananke'
defaultContentLanguageInSubdir = true
DefaultContentLanguage = "es"
SectionPagesMenu = "main"
# Paginate = 3 # this is set low for demonstrating with dummy content. Set to a higher number
# googleAnalytics = ""
enableRobotsTXT = true

[languages]
  [languages.es]
    title = "Laboratorio de Biometría y Modelación Forestal"
    languageCode = 'es-CL'
    weight = 1
    contentDir = "content/es"
    # languageDirection = 'rtl' for Right-To-Left languages
  [languages.en]
    title = "Biometrics Lab"
    languageCode = 'en-US'
    weight = 2
    contentDir = "content/en"

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  # text_color = ""
  # author = ""
  # favicon = ""
  # site_logo = ""
  description = "Sitio web del Laboratorio de Biometría y Modelación Forestal de la Facultad de Ciencias Forestales y de la Conservación de la Naturaleza, Universidad de Chile"
  # choose a background color from any on this page: https://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-black"
  recent_posts_number = 3

[[params.ananke_socials]]
# name = "twitter"
# url = "https://twitter.com/GoHugoIO"
